/* DO NOT EDIT THIS FILE - it is machine generated */
#include "include/jni.h"

//Java Package Name
//edu.internet.middleware

#ifndef _Included_JWrapper
#define _Included_JWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_internet_middleware_JWrapper
 * Method:    Initialize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_internet_middleware_JWrapper_Initialize(JNIEnv * env,jclass cls);

#ifdef __cplusplus
}
#endif
#endif



