/* DO NOT EDIT THIS FILE - it is machine generated */
#include "include/jni.h"

//Java Package Name
//edu.internet2.middleware.shibboleth.idp.authn.provider

#ifndef _Included_JWrapper
#define _Included_JWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_internet2_middleware_shibboleth_idp_authn_provider_JWrapper
 * Method:    Initialize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_internet2_middleware_shibboleth_idp_authn_provider_JWrapper_Initialize(JNIEnv * env,jclass cls);

#ifdef __cplusplus
}
#endif
#endif



